# fly.toml app configuration file generated for proud-wood-1032 on 2023-06-16T14:45:20+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

primary_region = "arn"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
